name = "diversity-careers"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "DC_DATA"
id = "c849f132892640a48b25bd6b2c6a9ea3"
preview_id = "f46992c71dc54d3d8f1cd3d9165525e1"
